// <auto-generated />
using System;
using Limping.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Limping.Api.Migrations
{
    [DbContext(typeof(LimpingDbContext))]
    [Migration("20190520135007_SetCascadeDelete")]
    partial class SetCascadeDelete
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Limping.Api.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("Limping.Api.Models.DataMigration", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("DataMigrations");
                });

            modelBuilder.Entity("Limping.Api.Models.LimpingTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppUserId");

                    b.Property<DateTime>("Date");

                    b.Property<Guid>("TestAnalysisId");

                    b.Property<string>("TestData");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("LimpingTests");
                });

            modelBuilder.Entity("Limping.Api.Models.TestAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<double>("EndValue");

                    b.Property<int>("LimpingSeverity");

                    b.Property<Guid>("LimpingTestId");

                    b.HasKey("Id");

                    b.HasIndex("LimpingTestId")
                        .IsUnique();

                    b.ToTable("TestAnalyses");
                });

            modelBuilder.Entity("Limping.Api.Models.LimpingTest", b =>
                {
                    b.HasOne("Limping.Api.Models.AppUser", "AppUser")
                        .WithMany("LimpingTests")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Limping.Api.Models.TestAnalysis", b =>
                {
                    b.HasOne("Limping.Api.Models.LimpingTest", "LimpingTest")
                        .WithOne("TestAnalysis")
                        .HasForeignKey("Limping.Api.Models.TestAnalysis", "LimpingTestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
