// <auto-generated />
using System;
using Limping.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Limping.Api.Migrations
{
    [DbContext(typeof(LimpingDbContext))]
    partial class LimpingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Limping.Api.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("Limping.Api.Models.DataMigration", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("DataMigrations");
                });

            modelBuilder.Entity("Limping.Api.Models.LimpingTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppUserId");

                    b.Property<DateTime>("Date");

                    b.Property<Guid>("TestAnalysisId");

                    b.Property<string>("TestData");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("LimpingTests");
                });

            modelBuilder.Entity("Limping.Api.Models.TestAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<double>("EndValue");

                    b.Property<int>("LimpingSeverity");

                    b.Property<Guid>("LimpingTestId");

                    b.HasKey("Id");

                    b.HasIndex("LimpingTestId")
                        .IsUnique();

                    b.ToTable("TestAnalyses");
                });

            modelBuilder.Entity("Limping.Api.Models.LimpingTest", b =>
                {
                    b.HasOne("Limping.Api.Models.AppUser", "AppUser")
                        .WithMany("LimpingTests")
                        .HasForeignKey("AppUserId");
                });

            modelBuilder.Entity("Limping.Api.Models.TestAnalysis", b =>
                {
                    b.HasOne("Limping.Api.Models.LimpingTest", "LimpingTest")
                        .WithOne("TestAnalysis")
                        .HasForeignKey("Limping.Api.Models.TestAnalysis", "LimpingTestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
